# DO NOT MODIFY THIS FILE!
# THIS FILE WAS AUTOGENERATED BY ISESTEROIDS AND WILL BE OVERWRITTEN WHEN YOU EXPORT FUNCTIONS TO THIS MODULE.

# USE THIS FILE FOR ADDITIONAL MODULE CODE. THIS FILE WILL NOT BE OVERWRITTEN
# WHEN NEW CONTENT IS PUBLISHED TO THIS MODULE:
. $PSScriptRoot\init.ps1

. $PSScriptRoot\ExcelFormating\GenericFormats.ps1
. $PSScriptRoot\ExcelFormating\BaseTemplate.ps1
. $PSScriptRoot\HTMLScraping\HealthCheckScraping.ps1
. $PSScriptRoot\ExcelDataFilling\DataToExcel.ps1
. $PSScriptRoot\Scoring\ScoreCalculations.ps1

New-Variable -Name HCRulesScheme -Value $HCRulesScheme -Scope Global -Force
New-Variable -Name IFPRESENT -Value $IFPRESENT -Scope Global -Force
New-Variable -Name IFCOUNT -Value $IFCOUNT -Scope Global -Force
New-Variable -Name IFOPERAND -Value $IFOPERAND -Scope Global -Force
New-Variable -Name HCRULESPATH -Value $PSScriptRoot\Resources\ad_hc_rules_list.html -Scope Global -Force
New-Variable -Name EXCELTEMPLATEPATH $PSScriptRoot\Resources\Plantilla.xlsx -Scope Global -Force